services:
  - type: web
    name: chef-ia-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn scr.main:app --host 0.0.0.0 --port 10000
    envVars:
      - key: GROQ_API_KEY
        sync: false # Debes pegarla manualmente en el panel de Render